# Tableau data pre-processing
The following code is for cleaning the Raw Data to make it presentable for Tableau presentation.
The dtaa type of Raw Data is a hierarchial index type. Unfortunatley, there is no orderly pattern for the index and columns. So, I have to enter the index and columns manually.

In [259]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

In [260]:
# the multi-index is not clean and iterable. I have to enter indexes manually.
# df_initial = pd.read_excel("test_DS.xlsx",sheet_name='df1')
data = pd.read_excel("test_DS.xlsx",sheet_name='data',header=None)

In [261]:
lead_type=['bncis','bncis','bncis','bncis','bncis','bncis','bncis','bncis','bncis','bncis','bncis',
                                    'bncis','bncis','bncis','bncis','bncis','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo','demo',
                                    'showroom','showroom','showroom','showroom','showroom','used','used','used','used','used','used','used','used','used','used','used','used','used','used','used']
device=['andriod', 'andriod','andriod','desktop','desktop','ipad','ipad','iphone','iphone','iphone','mobi','mobi','mobi' ,'other carsale network',
'unknown','unknown','andriod','andriod','andriod','desktop','desktop','ipad','ipad','iphone','iphone','iphone','mobi','mobi','mobi','other carsale network',
'unknown','unknown','android','desktop','ipad','iphone','mobi','android','android','android','desktop','desktop','ipad','ipad',
'iphone','iphone','iphone','mobi','mobi','mobi','unknown','unknown' ]
medium = ['call','call mobile','e-mail','call','e-mail','call','e-mail','call','call mobile','e-mail','call','call mobile',
'e-mail','e-mail','call','e-mail','call','call mobile','e-mail','call','e-mail','call','e-mail','call','call mobile','e-mail','call','call mobile',
'e-mail','e-mail','call','e-mail','e-mail','e-mail','e-mail','e-mail','e-mail','call','call mobile','e-mail','call','e-mail','call','e-mail',
'call','call mobile','e-mail','call','call mobile','e-mail','call','e-mail' ]

In [262]:
# index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
#                                    names=['year', 'visit'])
# columns = pd.MultiIndex.from_product([['2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2017','2017','2017','2017','2017','2017','2017','2017','2017','2017','2017'], [['January','February','March','April','May','June','July','August','September','October','November','December','January','February','March','April','May','June','July','August','September','October','November']]],
#                                      names=['year', 'month'])
columns=pd.MultiIndex.from_arrays([['2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2016','2017','2017','2017','2017','2017','2017','2017','2017','2017','2017','2017'], ['January','February','March','April','May','June','July','August','September','October','November','December','January','February','March','April','May','June','July','August','September','October','November']])
indexes=pd.MultiIndex.from_arrays([lead_type, device ,medium ])

# # create the DataFrame
df = pd.DataFrame(data.values, index=indexes, columns=columns)

In [263]:
df.head()

                              2016                                      \
                           January February    March    April      May
bncis andriod call             NaN      NaN      NaN      NaN      NaN
              call mobile      NaN      NaN      NaN      NaN      NaN
              e-mail           NaN      NaN      NaN      NaN      NaN
      desktop call             NaN      NaN      NaN      NaN      NaN
              e-mail       56430.0  50067.0  48663.0  43830.0  50409.0

                                                                         \
                              June     July   August September  October
bncis andriod call             NaN    571.0    581.0     591.0    601.0
              call mobile      NaN      NaN      NaN       NaN      NaN
              e-mail           NaN    200.0    220.0     240.0    260.0
      desktop call             NaN      NaN      NaN       NaN      3.0
              e-mail       50373.0  32643.0  31302.0   29313.0  32724.0

                            ...        2017                             \
                            ...    February    March    April      May
bncis andriod call          ...       641.0    651.0    661.0    671.0
              call mobile   ...         NaN      NaN      NaN      NaN
              e-mail        ...       340.0    360.0    380.0    400.0
      desktop call          ...        15.0     25.0     13.0     27.0
              e-mail        ...     37449.0  35802.0  29232.0  39672.0

                                                                         \
                              June     July   August September  October
bncis andriod call           681.0    691.0    701.0     711.0    721.0
              call mobile      NaN      NaN      NaN      14.0    101.0
              e-mail         420.0    440.0    460.0     480.0    500.0
      desktop call            18.0     15.0     20.0       4.0      2.0
              e-mail       42813.0  26982.0  24678.0   22473.0  23895.0


                          November
bncis andriod call           731.0
              call mobile    141.0
              e-mail         520.0
      desktop call             NaN
              e-mail       22680.0

[5 rows x 23 columns]

In [264]:
df=df.stack()
df=df.stack()
df

bncis  andriod  call         April      2017      661.0
                             August     2016      581.0
                                        2017      701.0
                             December   2016      621.0
                             February   2017      641.0
                             January    2017      631.0
                             July       2016      571.0
                                        2017      691.0
                             June       2017      681.0
                             March      2017      651.0
                             May        2017      671.0
                             November   2016      611.0
                                        2017      731.0
                             October    2016      601.0
                                        2017      721.0
                             September  2016      591.0
                                        2017      711.0
                call mobile  November   2017      141.0
                             October    2017      101.0
                             September  2017       14.0
                e-mail       April      2017      380.0
                             August     2016      220.0
                                        2017      460.0
                             December   2016      300.0
                             February   2017      340.0
                             January    2017      320.0
                             July       2016      200.0
                                        2017      440.0
                             June       2017      420.0
                             March      2017      360.0
                                                 ...
used   unknown  call         February   2017        5.0
                             January    2016     3788.0
                             June       2016     4755.0
                                        2017        2.0
                             March      2016     3512.0
                             May        2016     3700.0
                             November   2016        8.0
                                        2017        1.0
                             October    2016        2.0
                             September  2016        6.0
                                        2017        2.0
                e-mail       April      2016    48467.0
                                        2017       20.0
                             August     2016       43.0
                                        2017        1.0
                             December   2016       26.0
                             February   2016    49665.0
                                        2017       13.0
                             January    2016    53932.0
                                        2017       14.0
                             July       2016    17381.0
                             June       2016    45351.0
                             March      2016    49776.0
                                        2017        7.0
                             May        2016    48342.0
                                        2017        1.0
                             November   2016       37.0
                             October    2016       21.0
                             September  2016       33.0
                                        2017        4.0
Length: 735, dtype: float64

In [258]:
# df.reset_index(inplace=True)
# df = df.rename(columns={'level_0': 'lead_type', 'level_1': 'device', 'level_2': 'medium'})
# df.head()

In [265]:
df.to_csv('clean.csv')